


version : '3'
services :
  simple:
    build: .
    ports:
      - "2000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:3.4.2
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
volumes:
  data: